### ISSUE TITLE
Create images on the fly

### ISSUE THREAD

**Issue by Pascalmh** [S1SYPHOS/kirby-webp#4]
Why not create the images on-the-fly (like thumbs) instead of on upload?

**Comment by daybugging** [comment]
Could you explain your idea in a little detail? I'm intrigued, but as far as I'm concerned (and my clients), here are some thoughts:

Thumbnails may be created "on-the-fly", but only when & where _the developer_ pleases to. This approach **doesn't work on user-uploaded images**, when embedded in an article, so 1:0 for the "upload approach".

Another valid point might be that something like thumbnails requires overriding default behavior to some extend, even creating a Kirbytag would leave a customer with extra work, if one didn't want to override the image Kirbytag, which would be a possibility - but then, this doesn't do it for images _outside_ this context (eg, images being selected via Panel field).

jm2c

Suggestion: I'd love a "create WebP" widget / button in the Panel, removing all WebP images and then converting all uploaded PNGs / JPGs! (@FabianMichael's [ImageKit](https://github.com/fabianmichael/kirby-imagekit) might be a good starting point!)

**Comment by Pascalmh** [comment]
I extended the `(image:)`-tag here, so thats possible: https://github.com/Pascalmh/kirby-responsiveimage/blob/master/kirby-responsiveimage.php

So images in the `(image:)`-tag and images used through `$page->myimage()->toFile()` could be converted to webp and it would be plug-and-play - just install the plugin, your images are now webp if needed.

**Comment by S1SYPHOS** [comment]
That‘s an interesting idea, I will definitely look into this. This would also make @daybugging‘s widget obsolete, which I already thought about.

On the other hand, I guess this would lead to Incompatibility issues with plugins that are also extending or even overriding the image kirbytag?

**Comment by daybugging** [comment]
@Pascalmh, if you extend the image kirbytag, where is stuff saved then, the `thumbs` folder, even when they're not resized? Cache? I don't understand ..

**Comment by S1SYPHOS** [comment]
That‘s really up to us, what would you suggest? I guess thumbs folder is the way to go, no?

**Comment by Pascalmh** [comment]
Yeah I would say thumbs folder is the way to go. Maybe there is a way to use the routing for it? So if an .jpg/.png is called check if webp is supported and serve webp if possible.

**Comment by S1SYPHOS** [comment]
True dat

// Update:
But separating locations for regular images & webP versions, you'd have to massively change the `.htaccess` code where to look, on what path & so on. I'm no regex voodoo master, so it seems there's a bit of experimenting needed that I cannot provide right now.

A routing-based approach seems more interesting & platform-independent.
jm2c
