### ISSUE TITLE
Do not return anything inside hook

### ISSUE THREAD

**Issue by Pascalmh** [S1SYPHOS/kirby-webp#5]
> A hook is not expected to return anything. You cannot control the user flow with hooks at this state. They are silently triggered.
https://getkirby.com/docs/developer-guide/advanced/hooks

https://github.com/S1SYPHOS/kirby-webp/blob/master/core/generate_webp.php#L65

**Comment by daybugging** [comment]
How's it any different than [this](https://getkirby.com/docs/cookbook/handling-images-in-kirby#auto-resize-images-on-upload)?

**Comment by S1SYPHOS** [comment]
@daybugging: The thing is, `return` statements inside the `catch` block don't hurt. The example you are referring to just cares as much as Kirby does - not at all.
